#!/usr/bin/env bash
#
# Copyright 2017 - 2018 Ternaris
# SPDX-License-Identifier: Apache 2.0

set -e

if [[ -n "$GITLAB_CI" ]]; then
    exec "$@"
fi

if [[ -n "$DEBUG" ]]; then
    set -x
fi


if [[ -n "$TIMEZONE" ]]; then
    echo "$TIMEZONE" > /etc/timezone
    ln -sf /usr/share/zoneinfo/"$TIMEZONE" /etc/localtime
    dpkg-reconfigure -f noninteractive tzdata
fi

groupdel "$GROUP" &>/dev/null || true
groupadd -f -og "$GROUP_ID" "$GROUP"

if id "$USER" >/dev/null 2>&1; then
    echo 'User $USER found. Skipping creation'
else
    useradd -M -u "$USER_ID" -g "$GROUP_ID" -d "/home/$USER" -s /bin/bash "$USER"
fi

groupdel video &> /dev/null || true
groupadd -f -og "${VIDEO_GROUP_ID}" video
gpasswd -a "${USER}" video

echo "Adding user ${USER} to group dialout"
usermod -aG dialout ${USER}

if [[ -e /var/run/docker.sock ]]; then
    DOCKER_GROUP_ID=$(stat -c "%g" /var/run/docker.sock)
    groupadd -f -og ${DOCKER_GROUP_ID} docker
    echo "Adding user ${USER} to group docker"
    usermod -aG docker ${USER}
fi

for x in /etc/skel/.*; do
    target="/home/$USER/$(basename "$x")"
    if [[ ! -e "$target" ]]; then
	cp -a "$x" "$target"
	chown -R "$USER":"$GROUP" "$target"
    fi
done


if [[ -z "$SKIP_ADEINIT" ]]; then
    for x in /opt/*; do
	if [[ -x "$x/.adeinit" ]]; then
	    echo "Initializing $x"
	    sudo -Hu "$USER" -- bash -lc "$x/.adeinit"
	    echo "Initializing $x done"
	fi
    done
fi

echo 'ADE startup completed.'
exec "$@"
